### ISSUE TITLE
U2Net model (link broken)

### ISSUE THREAD

**Issue by spyrosavl** [ddgoede/Re-CGN#36]
Hi team,
Nice work! I am trying to reproduce your results but I can not download the U2Net model from https://github.com/danilodegoede/fact-team3/blob/main/cgn_framework/scripts/download_weights.sh . It seems that the first link is broken. I see that you are using the same link with the original paper. Was it functional when you did this study?
Thank you,
Spyros

**Comment by bpiyush** [comment]
Hi Spyros,

It seems that the public access to the link may have been revoked for some reason. Alternatively, you can download the model from U2Net's repository [here](https://drive.google.com/file/d/1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ/view). The repo link is [here](https://github.com/xuebinqin/U-2-Net). Hope this helps!

(We tried automating this bit via the new link - but `gdown` causes permission issues so best to download it manually, for now.)

**Comment by spyrosavl** [comment]
Thank you Piyush!
